version: '3'

services:
  db-staging:
    container_name: batch_postgres
    image: postgres:latest
    networks:
      - db_network
    environment:
      - POSTGRES_USER=${POSTGRES_STAGING_USER}
      - POSTGRES_PASSWORD=${POSTGRES_STAGING_PASSWORD}
      - POSTGRES_DB=${POSTGRES_STAGING_DB}
    ports:
      - "7003:5432"
    volumes:
      - ./db-staging:/var/lib/postgresql/data

  db-dwh:
    container_name: DWH_postgres
    image: 'postgres:latest'
    networks:
      - db_network
    restart: always
    ports:
      - "7001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_DWH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DWH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DWH_DB}
    volumes:
     - ./db-dwh:/var/lib/postgresql/data

networks:
  db_network:
    driver: bridge

volumes:
  db-staging:
    name: db-staging-data
  db-dwh:
    name: db-dwh-data