version: '3'

services:
  db-dwh:
    image: 'postgres:latest'
    restart: always
    networks:
      - pipe_network
    ports:
      - "6000:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_DWH_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DWH_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DWH_DB}
    volumes:
     - ./db-dwh:/var/lib/postgresql/data

  db-data-mart:
    image: 'postgres:latest'
    restart: always
    networks:
      - pipe_network
    ports:
      - "6001:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER_DATA_MART}
      - POSTGRES_DB==${POSTGRES_DB_DATA_MART}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DATA_MART}
    volumes:
     - ./db-data-mart:/var/lib/postgresql/data

networks:
  pipe_network:
    driver: bridge

volumes:
  db-dwh:
    name: db-dwh-data
  db-data-mart:
    name: db-data-mart-data